export class SubjectConstants {
  public static readonly MATEMATIKA = 'Matematika'
  public static readonly ALGEBRA = 'Algebra'
  public static readonly GEOMETRIYA = 'Geometriya'
  public static readonly FIZIKA = 'Fizika'
  public static readonly KIMYO = 'Kimyo'
  public static readonly BIOLOGIYA = 'Biologiya'
  public static readonly INFORMATIKA = 'Informatika'
  public static readonly INGLIZ_TILI = 'Ingliz tili'
  public static readonly ONA_TILI = 'Ona tili'
  public static readonly RUS_TILI = 'Rus tili'
  public static readonly TARIX = 'Tarix'
  public static readonly GEOGRAFIYA = 'Geografiya'
  public static readonly ADABIYOT = 'Adabiyot'
  public static readonly IQTISODIYOT = 'Iqtisodiyot'
  public static readonly HUQUQ = 'Huquq'
  public static readonly CHIZMACHILIK = 'Chizmachilik'
  public static readonly TARBIYA = 'Tarbiya'
}
